
### Check health
GET http://localhost:3001/api/health

### Register Client
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
	"email": "client1@example.com",
	"password": "StrongPass123!",
	"role": "client"
}

### Register therapist
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
	"email": "therapist@example.com",
	"password": "StrongPass123!",
	"role": "therapist"
}

### Verify Email
POST http://localhost:3001/api/auth/verify-email
Content-Type: application/json

{
	"token": "paste_verification_token_here"
}

### Login client
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
	"email": "client1@example.com",
	"password": "StrongPass123!"
}

### Login therapist
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
	"email": "therapist@example.com",
	"password": "StrongPass123!"
}

### Refresh Token
POST http://localhost:3001/api/auth/refresh
Content-Type: application/json

{
	"refreshToken": "paste_refresh_token_here"
}

### Me (JWT required)
GET http://localhost:3001/api/auth/me
Authorization: Bearer paste_verification_token_here

### Client Booking Request (client JWT)
POST http://localhost:3001/api/sessions/booking-requests
Authorization: Bearer paste_verification_token_here
Content-Type: application/json

{
	"therapistId": "Therapist ID",
	"startAtUtc": "2026-05-20T10:00:00.000Z"
}

### Therapist queue (therapist JWT)
# TODO: 
GET http://localhost:3001/api/sessions/therapist-queue
Authorization: Bearer paste_verification_token_here
Content-Type: application/json

{
	
}

### List Services
GET http://localhost:3001/api/public/services?locale=en

### List Therapists
GET http://localhost:3001/api/public/therapists?locale=en

### Get Therapist by Slug
# /public/therapists/therapist-slug?locale=en
GET http://localhost:3001/api/public/therapists/ana-jovanovic?locale=en

### List Blog Posts
GET http://localhost:3001/api/public/blog?locale=en

### Get Blog Post by Slug
GET http://localhost:3001/api/public/blog/post-slug?locale=en

### List FAQ Entries
GET http://localhost:3001/api/public/faq?locale=en

### Create Contact Inquiry
POST http://localhost:3001/api/public/contact-inquiries
Content-Type: application/json

{
	"name": "John Doe",
	"email": "john@example.com",
	"message": "I would like to schedule a session.",
	"locale": "en",
	"therapistSlug": "john-doe"
}
